import "./globals.css";
import { Navbar,Footer } from "@/components";

export const metadata = {
  title: "DoorDash Food Delivery & Takeout - From Restaurants Near You",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
